name: Run Code

on:
  schedule:
    - cron: '0 12 * * *' # 设置定时运行，每天 UTC 时间的 00:00 运行
  workflow_dispatch: # 添加手动触发器

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        API_USER: ${{ secrets.API_USER }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: python main.py
